version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PW
      - TAG_VER="v1.0.52"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$TAG_VER .
      - docker tag $IMAGE_REPO_NAME:$TAG_VER $IMAGE_REPO_NAME:$TAG_VER
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$TAG_VER
      - echo Writing image definitions file...
      - printf '[{"name":"devops-flask","imageUri":"%s"}]' $IMAGE_REPO_NAME:$TAG_VER > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
